image:
  file: .gitpod.Dockerfile

# Use 'lock file' to delay running ddev until it is installed
# https://www.gitpod.io/blog/gitpodify/#running-init-scripts
tasks:
  # Wait 5 seconds for `sudo docker-up` to run, before starting ddev
  - name: ddev_run
    command: |
      sleep 5
      .ddev/gitpod-setup-ddev.sh
  - init:
    command: |
      composer install
      sudo apt update && sudo apt install -y python3 python3-pip libxext6 libxrender1 libxtst6 libfreetype6 libxi6
      pip3 install projector-installer --user
      printf "8\ny\n3\n" | projector install & # Fragile - will break when they change options
  - name: docker_up
    command: sudo docker-up


# Set the following ports public
ports:
  - port: 8080
  - port: 8025
    onOpen: ignore
  - port: 8026
    onOpen: ignore
  - port: 8036
    onOpen: ignore
  - port: 8037
    onOpen: ignore
  - port: 8443
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true
