name: ddev-gitpod
type: drupal9
docroot: web
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "8888"
router_https_port: "8889"
mariadb_version: "10.3"
mysql_version: ""
use_dns_when_possible: false
